version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db_auth
    restart: always
    environment:
      POSTGRES_USER: kapital
      POSTGRES_PASSWORD: kapital
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ms-auth:
    build: .
    container_name: ms_auth_service
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: auth
      POSTGRES_USER: kapital
      POSTGRES_PASSWORD: kapital
    ports:
      - "8002:8002"

volumes:
  postgres_data: