spring:
  application:
    name: transfer-ms
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    username: kapital
    password: kapital
    url: jdbc:postgresql://localhost:5432/transfer
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

server:
  port: 8001
  servlet:
    context-path: /transfer

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/transfer
    username: kapital
    password: kapital
    driver-class-name: org.postgresql.Driver
  drop-first: false

