spring:
    application:
      name: gateway
    main:
      web-application-type: reactive
    cloud:
      gateway:
        routes:
          - id: transfer-ms
            uri: lb://TRANSFER-MS
            predicates:
              - Path=/transfer-management/**
            filters:
              - AuthFilter

          - id: auth-ms
            uri: lb://AUTH-MS
            predicates:
              - Path=/auth-management/**

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
server:
  port: 8080

jwt:
  secret: 3cisNpEbyZZUIp83H12iCuSP9yCnCYvYy5rWIcy8zoKgkeLaqr3cisNpEbyZZUIp83H12iCuSP9yCnCYvYy5rWIcy8zoKgkeLaqr